FROM openjdk:8-alpine
FROM maven:3.6.1-jdk-8
EXPOSE 8080
ADD ./review-service ./rewiev-service
RUN mvn clean install -U -f review-service/pom.xml -DskipTests
ENTRYPOINT ["java","-jar","review-service/target/pubweb-review-service-1.0.0.jar"]
