version: '3'

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  web:
    build: .
    depends_on: 
      - db
    ports:
      - "5000:5000"
