apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Paweł\Desktop\kompose-windows-amd64.exe convert -f .\docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: pubizr
        - name: POSTGRES_PASSWORD
          value: Bla123_user
        - name: POSTGRES_USER
          value: pubizr_user
        image: postgres
        name: db
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
