apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Paweł\Desktop\kompose-windows-amd64.exe convert -f .\docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
