apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Paweł\Desktop\kompose-windows-amd64.exe convert -f .\docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: user-service
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "5432"
        - name: REGISTRY_HOST
          value: eureka-serviceregistry
        image: user-service
        name: user-service
        ports:
        - containerPort: 8096
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
